#!/bin/bash

_usage() {
    echo "Usage: git latest <branch>" 1>&2
    exit 1
}

_latest() {
    echo git merge-ff $1 origin/$1
    git merge-ff $1 origin/$1
}

case $# in
    1 ) case "$1" in
            -a | --all )
                git for-each-ref --format='%(refname:short)' refs/heads/ | while read branch ; do
                    _latest $branch
                done;;
            * ) _latest "$1";;
        esac;;
    * ) _usage
esac