#!/bin/bash

_usage() {
    echo "Usage: git has  <committish> [--not/-n <committish>]" 1>&2
    exit 1
}

_has_not(){
	git branch -$branch_flags --contains $1 | grep -vF "$(git branch -$branch_flags --contains $2)"
}

_has(){
	git branch -$branch_flags --contains $1 
}

while getopts ":alr" opt; do
	case $opt in
		l | r)
			branch_flags=$branch_flags$opt
			;;
		\?)
			echo "Invalid option -$OPTARG" >&2
			_usage
			;;
	esac
done
shift $((OPTIND-1))

if [ "$branch_flags" = "" ]; then
	branch_flags="a"
fi

case $# in
    3 ) _has_not "$1" "$3";;
    1 ) _has "$1";;
    * ) _usage
esac
